[package]
name = "hoppy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gamercade_rs = "0.1.1"
hecs = "0.9.0"
rapier2d = "0.14.0"

[profile.release]
lto = true